language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - cd ambev
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

# deploy:
#   provider: firebase
#   token:
#     secure: "Vz+VOEvBX+G8y4C7zrhq3r+P0FC1Npi4KsilIWWwVhpyH2M4t7N7QZcP/B2wAGgMm5/6CeKWXOH4s8rBhNwoEaqZmK47/H+4Hu1ghr6LHBRDh4HQNtJMB/7Q3OLRHHJdHO7AIKOCr+S3g3o8Bsm4gpybvp7b52AE7rQqFSmr1mkzSz8I6tqEcbdCedQsJD5lIcFSPZaIA9F+/nICjJunnVbmjcKqQl9xJBa9huSXZGuAFVXuI+hwWRw+SuRl5bURNF3rbtPPV9uSJvheXxEyW5tLIgWEtO8TT++M4sM8NM6Q+nRuFIcV/2mLwWhyukhBKetA3/8GZp9+LWI4mCPVNVTwM2NSUdO8gnjB9TYP7iIsZda0ltvfWkUXV1QZ3o8gX0PQZwGpdFeWn5gM02rgUPztf/LU0zVzfR3DZ6+kvh+Ezld5kROH1eFWA5hs58kMmTcYCz/qsi0PIzXrDhsZw7DXt1KZqDawNoYwRAFnkJ4bBY2UOw0Cb7NC6iS5WHExgO/dFFFtozWLHFSduWu5MgGDVMBqnr8+YwbqtwP59tWyOAA3UsPhTWkql720rD4XW7Fp+Cgh6lkwgL8ycOlwdKg7tkLesE1+85xAlcVv0A5DaXml9oxXfQUFxZjPbtzDnsi3UYufGaMrrFRit3m0YessmmfmnPsL+wheI4C7JPQ="
